### ISSUE TITLE
Norme fail

### ISSUE THREAD

**Issue by celeloup** [jtoty/Libftest#26] opened 2019-12-03 12:15 UTC
The norm keep failing.
It's testing the name of the file without the .c
Example :
`= ft_atoi ======================================================================
$> norminette ft_atoi | grep -E '(Error|Warning)'
Warning: Not a valid file
Norme check failed`

Written ft_atoi instead of ft_atoi.c

**Comment by jtoty** [comment] 2019-12-04 00:28
Forgot to add `.c` extension.
Should be fixed now, but the name of the file must be the same than the function name, otherwise it doesn't find the file (e.g: ft_atoi.c for ft_atoi)
Thinking to a solution to test norm if the file name is not the same of the function
If the problem is not solved, you can disable testing norm with -n option (cf readme)
Thank you for the issue

**Closed as completed** 2019-12-04 10:03 UTC
